//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.02 at 04:43:05 PM EST 
//


package MusicXMLClasses;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}footnote"/&gt;
 *         &lt;element ref="{}level"/&gt;
 *         &lt;element ref="{}divisions"/&gt;
 *         &lt;element ref="{}key"/&gt;
 *         &lt;element ref="{}time"/&gt;
 *         &lt;element ref="{}staves"/&gt;
 *         &lt;element ref="{}part-symbol"/&gt;
 *         &lt;element ref="{}instruments"/&gt;
 *         &lt;element ref="{}clef"/&gt;
 *         &lt;element ref="{}staff-details"/&gt;
 *         &lt;element ref="{}transpose"/&gt;
 *         &lt;element ref="{}directive"/&gt;
 *         &lt;element ref="{}measure-style"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "footnote",
    "level",
    "divisions",
    "key",
    "time",
    "staves",
    "partSymbol",
    "instruments",
    "clef",
    "staffDetails",
    "transpose",
    "directive",
    "measureStyle"
})
@XmlRootElement(name = "attributes")
public class Attributes {

    @XmlElement(required = true)
    protected Footnote footnote;
    @XmlElement(required = true)
    protected Level level;
    @XmlElement(required = true)
    protected BigDecimal divisions;
    @XmlElement(required = true)
    protected Key key;
    @XmlElement(required = true)
    protected Time time;
    @XmlElement(required = true)
    protected BigInteger staves;
    @XmlElement(name = "part-symbol", required = true)
    protected PartSymbol partSymbol;
    @XmlElement(required = true)
    protected BigInteger instruments;
    @XmlElement(required = true)
    protected Clef clef;
    @XmlElement(name = "staff-details", required = true)
    protected StaffDetails staffDetails;
    @XmlElement(required = true)
    protected Transpose transpose;
    @XmlElement(required = true)
    protected Directive directive;
    @XmlElement(name = "measure-style", required = true)
    protected MeasureStyle measureStyle;

    /**
     * Gets the value of the footnote property.
     * 
     * @return
     *     possible object is
     *     {@link Footnote }
     *     
     */
    public Footnote getFootnote() {
        return footnote;
    }

    /**
     * Sets the value of the footnote property.
     * 
     * @param value
     *     allowed object is
     *     {@link Footnote }
     *     
     */
    public void setFootnote(Footnote value) {
        this.footnote = value;
    }

    /**
     * Gets the value of the level property.
     * 
     * @return
     *     possible object is
     *     {@link Level }
     *     
     */
    public Level getLevel() {
        return level;
    }

    /**
     * Sets the value of the level property.
     * 
     * @param value
     *     allowed object is
     *     {@link Level }
     *     
     */
    public void setLevel(Level value) {
        this.level = value;
    }

    /**
     * Gets the value of the divisions property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDivisions() {
        return divisions;
    }

    /**
     * Sets the value of the divisions property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDivisions(BigDecimal value) {
        this.divisions = value;
    }

    /**
     * Gets the value of the key property.
     * 
     * @return
     *     possible object is
     *     {@link Key }
     *     
     */
    public Key getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     * 
     * @param value
     *     allowed object is
     *     {@link Key }
     *     
     */
    public void setKey(Key value) {
        this.key = value;
    }

    /**
     * Gets the value of the time property.
     * 
     * @return
     *     possible object is
     *     {@link Time }
     *     
     */
    public Time getTime() {
        return time;
    }

    /**
     * Sets the value of the time property.
     * 
     * @param value
     *     allowed object is
     *     {@link Time }
     *     
     */
    public void setTime(Time value) {
        this.time = value;
    }

    /**
     * Gets the value of the staves property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getStaves() {
        return staves;
    }

    /**
     * Sets the value of the staves property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setStaves(BigInteger value) {
        this.staves = value;
    }

    /**
     * Gets the value of the partSymbol property.
     * 
     * @return
     *     possible object is
     *     {@link PartSymbol }
     *     
     */
    public PartSymbol getPartSymbol() {
        return partSymbol;
    }

    /**
     * Sets the value of the partSymbol property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartSymbol }
     *     
     */
    public void setPartSymbol(PartSymbol value) {
        this.partSymbol = value;
    }

    /**
     * Gets the value of the instruments property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getInstruments() {
        return instruments;
    }

    /**
     * Sets the value of the instruments property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setInstruments(BigInteger value) {
        this.instruments = value;
    }

    /**
     * Gets the value of the clef property.
     * 
     * @return
     *     possible object is
     *     {@link Clef }
     *     
     */
    public Clef getClef() {
        return clef;
    }

    /**
     * Sets the value of the clef property.
     * 
     * @param value
     *     allowed object is
     *     {@link Clef }
     *     
     */
    public void setClef(Clef value) {
        this.clef = value;
    }

    /**
     * Gets the value of the staffDetails property.
     * 
     * @return
     *     possible object is
     *     {@link StaffDetails }
     *     
     */
    public StaffDetails getStaffDetails() {
        return staffDetails;
    }

    /**
     * Sets the value of the staffDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link StaffDetails }
     *     
     */
    public void setStaffDetails(StaffDetails value) {
        this.staffDetails = value;
    }

    /**
     * Gets the value of the transpose property.
     * 
     * @return
     *     possible object is
     *     {@link Transpose }
     *     
     */
    public Transpose getTranspose() {
        return transpose;
    }

    /**
     * Sets the value of the transpose property.
     * 
     * @param value
     *     allowed object is
     *     {@link Transpose }
     *     
     */
    public void setTranspose(Transpose value) {
        this.transpose = value;
    }

    /**
     * Gets the value of the directive property.
     * 
     * @return
     *     possible object is
     *     {@link Directive }
     *     
     */
    public Directive getDirective() {
        return directive;
    }

    /**
     * Sets the value of the directive property.
     * 
     * @param value
     *     allowed object is
     *     {@link Directive }
     *     
     */
    public void setDirective(Directive value) {
        this.directive = value;
    }

    /**
     * Gets the value of the measureStyle property.
     * 
     * @return
     *     possible object is
     *     {@link MeasureStyle }
     *     
     */
    public MeasureStyle getMeasureStyle() {
        return measureStyle;
    }

    /**
     * Sets the value of the measureStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeasureStyle }
     *     
     */
    public void setMeasureStyle(MeasureStyle value) {
        this.measureStyle = value;
    }

}
