//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.02 at 04:43:05 PM EST 
//


package MusicXMLClasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}encoding-date"/&gt;
 *         &lt;element ref="{}encoder"/&gt;
 *         &lt;element ref="{}software"/&gt;
 *         &lt;element ref="{}encoding-description"/&gt;
 *         &lt;element ref="{}supports"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "encodingDate",
    "encoder",
    "software",
    "encodingDescription",
    "supports"
})
@XmlRootElement(name = "encoding")
public class Encoding {

    @XmlElement(name = "encoding-date", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected java.lang.String encodingDate;
    @XmlElement(required = true)
    protected Encoder encoder;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected java.lang.String software;
    @XmlElement(name = "encoding-description", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected java.lang.String encodingDescription;
    @XmlElement(required = true)
    protected Supports supports;

    /**
     * Gets the value of the encodingDate property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getEncodingDate() {
        return encodingDate;
    }

    /**
     * Sets the value of the encodingDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setEncodingDate(java.lang.String value) {
        this.encodingDate = value;
    }

    /**
     * Gets the value of the encoder property.
     * 
     * @return
     *     possible object is
     *     {@link Encoder }
     *     
     */
    public Encoder getEncoder() {
        return encoder;
    }

    /**
     * Sets the value of the encoder property.
     * 
     * @param value
     *     allowed object is
     *     {@link Encoder }
     *     
     */
    public void setEncoder(Encoder value) {
        this.encoder = value;
    }

    /**
     * Gets the value of the software property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getSoftware() {
        return software;
    }

    /**
     * Sets the value of the software property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setSoftware(java.lang.String value) {
        this.software = value;
    }

    /**
     * Gets the value of the encodingDescription property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getEncodingDescription() {
        return encodingDescription;
    }

    /**
     * Sets the value of the encodingDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setEncodingDescription(java.lang.String value) {
        this.encodingDescription = value;
    }

    /**
     * Gets the value of the supports property.
     * 
     * @return
     *     possible object is
     *     {@link Supports }
     *     
     */
    public Supports getSupports() {
        return supports;
    }

    /**
     * Sets the value of the supports property.
     * 
     * @param value
     *     allowed object is
     *     {@link Supports }
     *     
     */
    public void setSupports(Supports value) {
        this.supports = value;
    }

}
