//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.02 at 04:43:05 PM EST 
//


package MusicXMLClasses;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}midi-channel"/&gt;
 *         &lt;element ref="{}midi-name"/&gt;
 *         &lt;element ref="{}midi-bank"/&gt;
 *         &lt;element ref="{}midi-program"/&gt;
 *         &lt;element ref="{}midi-unpitched"/&gt;
 *         &lt;element ref="{}volume"/&gt;
 *         &lt;element ref="{}pan"/&gt;
 *         &lt;element ref="{}elevation"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "midiChannel",
    "midiName",
    "midiBank",
    "midiProgram",
    "midiUnpitched",
    "volume",
    "pan",
    "elevation"
})
@XmlRootElement(name = "midi-instrument")
public class MidiInstrument {

    @XmlElement(name = "midi-channel", required = true)
    protected BigInteger midiChannel;
    @XmlElement(name = "midi-name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected java.lang.String midiName;
    @XmlElement(name = "midi-bank", required = true)
    protected BigInteger midiBank;
    @XmlElement(name = "midi-program", required = true)
    protected BigInteger midiProgram;
    @XmlElement(name = "midi-unpitched", required = true)
    protected BigInteger midiUnpitched;
    @XmlElement(required = true)
    protected BigInteger volume;
    @XmlElement(required = true)
    protected BigInteger pan;
    @XmlElement(required = true)
    protected BigInteger elevation;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected java.lang.String id;

    /**
     * Gets the value of the midiChannel property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMidiChannel() {
        return midiChannel;
    }

    /**
     * Sets the value of the midiChannel property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMidiChannel(BigInteger value) {
        this.midiChannel = value;
    }

    /**
     * Gets the value of the midiName property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getMidiName() {
        return midiName;
    }

    /**
     * Sets the value of the midiName property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setMidiName(java.lang.String value) {
        this.midiName = value;
    }

    /**
     * Gets the value of the midiBank property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMidiBank() {
        return midiBank;
    }

    /**
     * Sets the value of the midiBank property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMidiBank(BigInteger value) {
        this.midiBank = value;
    }

    /**
     * Gets the value of the midiProgram property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMidiProgram() {
        return midiProgram;
    }

    /**
     * Sets the value of the midiProgram property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMidiProgram(BigInteger value) {
        this.midiProgram = value;
    }

    /**
     * Gets the value of the midiUnpitched property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMidiUnpitched() {
        return midiUnpitched;
    }

    /**
     * Sets the value of the midiUnpitched property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMidiUnpitched(BigInteger value) {
        this.midiUnpitched = value;
    }

    /**
     * Gets the value of the volume property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVolume() {
        return volume;
    }

    /**
     * Sets the value of the volume property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVolume(BigInteger value) {
        this.volume = value;
    }

    /**
     * Gets the value of the pan property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPan() {
        return pan;
    }

    /**
     * Sets the value of the pan property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPan(BigInteger value) {
        this.pan = value;
    }

    /**
     * Gets the value of the elevation property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getElevation() {
        return elevation;
    }

    /**
     * Sets the value of the elevation property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setElevation(BigInteger value) {
        this.elevation = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setId(java.lang.String value) {
        this.id = value;
    }

}
