//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.02 at 04:43:05 PM EST 
//


package MusicXMLClasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}trill-mark"/&gt;
 *         &lt;element ref="{}turn"/&gt;
 *         &lt;element ref="{}delayed-turn"/&gt;
 *         &lt;element ref="{}inverted-turn"/&gt;
 *         &lt;element ref="{}delayed-inverted-turn"/&gt;
 *         &lt;element ref="{}vertical-turn"/&gt;
 *         &lt;element ref="{}inverted-vertical-turn"/&gt;
 *         &lt;element ref="{}shake"/&gt;
 *         &lt;element ref="{}wavy-line"/&gt;
 *         &lt;element ref="{}mordent"/&gt;
 *         &lt;element ref="{}inverted-mordent"/&gt;
 *         &lt;element ref="{}schleifer"/&gt;
 *         &lt;element ref="{}tremolo"/&gt;
 *         &lt;element ref="{}haydn"/&gt;
 *         &lt;element ref="{}other-ornament"/&gt;
 *         &lt;element ref="{}accidental-mark"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "trillMark",
    "turn",
    "delayedTurn",
    "invertedTurn",
    "delayedInvertedTurn",
    "verticalTurn",
    "invertedVerticalTurn",
    "shake",
    "wavyLine",
    "mordent",
    "invertedMordent",
    "schleifer",
    "tremolo",
    "haydn",
    "otherOrnament",
    "accidentalMark"
})
@XmlRootElement(name = "ornaments")
public class Ornaments {

    @XmlElement(name = "trill-mark", required = true)
    protected TrillMark trillMark;
    @XmlElement(required = true)
    protected Turn turn;
    @XmlElement(name = "delayed-turn", required = true)
    protected DelayedTurn delayedTurn;
    @XmlElement(name = "inverted-turn", required = true)
    protected InvertedTurn invertedTurn;
    @XmlElement(name = "delayed-inverted-turn", required = true)
    protected DelayedInvertedTurn delayedInvertedTurn;
    @XmlElement(name = "vertical-turn", required = true)
    protected VerticalTurn verticalTurn;
    @XmlElement(name = "inverted-vertical-turn", required = true)
    protected InvertedVerticalTurn invertedVerticalTurn;
    @XmlElement(required = true)
    protected Shake shake;
    @XmlElement(name = "wavy-line", required = true)
    protected WavyLine wavyLine;
    @XmlElement(required = true)
    protected Mordent mordent;
    @XmlElement(name = "inverted-mordent", required = true)
    protected InvertedMordent invertedMordent;
    @XmlElement(required = true)
    protected Schleifer schleifer;
    @XmlElement(required = true)
    protected Tremolo tremolo;
    @XmlElement(required = true)
    protected Haydn haydn;
    @XmlElement(name = "other-ornament", required = true)
    protected OtherOrnament otherOrnament;
    @XmlElement(name = "accidental-mark", required = true)
    protected AccidentalMark accidentalMark;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected java.lang.String id;

    /**
     * Gets the value of the trillMark property.
     * 
     * @return
     *     possible object is
     *     {@link TrillMark }
     *     
     */
    public TrillMark getTrillMark() {
        return trillMark;
    }

    /**
     * Sets the value of the trillMark property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrillMark }
     *     
     */
    public void setTrillMark(TrillMark value) {
        this.trillMark = value;
    }

    /**
     * Gets the value of the turn property.
     * 
     * @return
     *     possible object is
     *     {@link Turn }
     *     
     */
    public Turn getTurn() {
        return turn;
    }

    /**
     * Sets the value of the turn property.
     * 
     * @param value
     *     allowed object is
     *     {@link Turn }
     *     
     */
    public void setTurn(Turn value) {
        this.turn = value;
    }

    /**
     * Gets the value of the delayedTurn property.
     * 
     * @return
     *     possible object is
     *     {@link DelayedTurn }
     *     
     */
    public DelayedTurn getDelayedTurn() {
        return delayedTurn;
    }

    /**
     * Sets the value of the delayedTurn property.
     * 
     * @param value
     *     allowed object is
     *     {@link DelayedTurn }
     *     
     */
    public void setDelayedTurn(DelayedTurn value) {
        this.delayedTurn = value;
    }

    /**
     * Gets the value of the invertedTurn property.
     * 
     * @return
     *     possible object is
     *     {@link InvertedTurn }
     *     
     */
    public InvertedTurn getInvertedTurn() {
        return invertedTurn;
    }

    /**
     * Sets the value of the invertedTurn property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvertedTurn }
     *     
     */
    public void setInvertedTurn(InvertedTurn value) {
        this.invertedTurn = value;
    }

    /**
     * Gets the value of the delayedInvertedTurn property.
     * 
     * @return
     *     possible object is
     *     {@link DelayedInvertedTurn }
     *     
     */
    public DelayedInvertedTurn getDelayedInvertedTurn() {
        return delayedInvertedTurn;
    }

    /**
     * Sets the value of the delayedInvertedTurn property.
     * 
     * @param value
     *     allowed object is
     *     {@link DelayedInvertedTurn }
     *     
     */
    public void setDelayedInvertedTurn(DelayedInvertedTurn value) {
        this.delayedInvertedTurn = value;
    }

    /**
     * Gets the value of the verticalTurn property.
     * 
     * @return
     *     possible object is
     *     {@link VerticalTurn }
     *     
     */
    public VerticalTurn getVerticalTurn() {
        return verticalTurn;
    }

    /**
     * Sets the value of the verticalTurn property.
     * 
     * @param value
     *     allowed object is
     *     {@link VerticalTurn }
     *     
     */
    public void setVerticalTurn(VerticalTurn value) {
        this.verticalTurn = value;
    }

    /**
     * Gets the value of the invertedVerticalTurn property.
     * 
     * @return
     *     possible object is
     *     {@link InvertedVerticalTurn }
     *     
     */
    public InvertedVerticalTurn getInvertedVerticalTurn() {
        return invertedVerticalTurn;
    }

    /**
     * Sets the value of the invertedVerticalTurn property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvertedVerticalTurn }
     *     
     */
    public void setInvertedVerticalTurn(InvertedVerticalTurn value) {
        this.invertedVerticalTurn = value;
    }

    /**
     * Gets the value of the shake property.
     * 
     * @return
     *     possible object is
     *     {@link Shake }
     *     
     */
    public Shake getShake() {
        return shake;
    }

    /**
     * Sets the value of the shake property.
     * 
     * @param value
     *     allowed object is
     *     {@link Shake }
     *     
     */
    public void setShake(Shake value) {
        this.shake = value;
    }

    /**
     * Gets the value of the wavyLine property.
     * 
     * @return
     *     possible object is
     *     {@link WavyLine }
     *     
     */
    public WavyLine getWavyLine() {
        return wavyLine;
    }

    /**
     * Sets the value of the wavyLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link WavyLine }
     *     
     */
    public void setWavyLine(WavyLine value) {
        this.wavyLine = value;
    }

    /**
     * Gets the value of the mordent property.
     * 
     * @return
     *     possible object is
     *     {@link Mordent }
     *     
     */
    public Mordent getMordent() {
        return mordent;
    }

    /**
     * Sets the value of the mordent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Mordent }
     *     
     */
    public void setMordent(Mordent value) {
        this.mordent = value;
    }

    /**
     * Gets the value of the invertedMordent property.
     * 
     * @return
     *     possible object is
     *     {@link InvertedMordent }
     *     
     */
    public InvertedMordent getInvertedMordent() {
        return invertedMordent;
    }

    /**
     * Sets the value of the invertedMordent property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvertedMordent }
     *     
     */
    public void setInvertedMordent(InvertedMordent value) {
        this.invertedMordent = value;
    }

    /**
     * Gets the value of the schleifer property.
     * 
     * @return
     *     possible object is
     *     {@link Schleifer }
     *     
     */
    public Schleifer getSchleifer() {
        return schleifer;
    }

    /**
     * Sets the value of the schleifer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Schleifer }
     *     
     */
    public void setSchleifer(Schleifer value) {
        this.schleifer = value;
    }

    /**
     * Gets the value of the tremolo property.
     * 
     * @return
     *     possible object is
     *     {@link Tremolo }
     *     
     */
    public Tremolo getTremolo() {
        return tremolo;
    }

    /**
     * Sets the value of the tremolo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tremolo }
     *     
     */
    public void setTremolo(Tremolo value) {
        this.tremolo = value;
    }

    /**
     * Gets the value of the haydn property.
     * 
     * @return
     *     possible object is
     *     {@link Haydn }
     *     
     */
    public Haydn getHaydn() {
        return haydn;
    }

    /**
     * Sets the value of the haydn property.
     * 
     * @param value
     *     allowed object is
     *     {@link Haydn }
     *     
     */
    public void setHaydn(Haydn value) {
        this.haydn = value;
    }

    /**
     * Gets the value of the otherOrnament property.
     * 
     * @return
     *     possible object is
     *     {@link OtherOrnament }
     *     
     */
    public OtherOrnament getOtherOrnament() {
        return otherOrnament;
    }

    /**
     * Sets the value of the otherOrnament property.
     * 
     * @param value
     *     allowed object is
     *     {@link OtherOrnament }
     *     
     */
    public void setOtherOrnament(OtherOrnament value) {
        this.otherOrnament = value;
    }

    /**
     * Gets the value of the accidentalMark property.
     * 
     * @return
     *     possible object is
     *     {@link AccidentalMark }
     *     
     */
    public AccidentalMark getAccidentalMark() {
        return accidentalMark;
    }

    /**
     * Sets the value of the accidentalMark property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccidentalMark }
     *     
     */
    public void setAccidentalMark(AccidentalMark value) {
        this.accidentalMark = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setId(java.lang.String value) {
        this.id = value;
    }

}
