//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.02 at 04:43:05 PM EST 
//


package MusicXMLClasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}instrument-name"/&gt;
 *         &lt;element ref="{}instrument-abbreviation"/&gt;
 *         &lt;element ref="{}instrument-sound"/&gt;
 *         &lt;element ref="{}solo"/&gt;
 *         &lt;element ref="{}ensemble"/&gt;
 *         &lt;element ref="{}virtual-instrument"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "instrumentName",
    "instrumentAbbreviation",
    "instrumentSound",
    "solo",
    "ensemble",
    "virtualInstrument"
})
@XmlRootElement(name = "score-instrument")
public class ScoreInstrument {

    @XmlElement(name = "instrument-name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected java.lang.String instrumentName;
    @XmlElement(name = "instrument-abbreviation", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected java.lang.String instrumentAbbreviation;
    @XmlElement(name = "instrument-sound", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected java.lang.String instrumentSound;
    @XmlElement(required = true)
    protected Solo solo;
    @XmlElement(required = true)
    protected java.lang.String ensemble;
    @XmlElement(name = "virtual-instrument", required = true)
    protected VirtualInstrument virtualInstrument;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected java.lang.String id;

    /**
     * Gets the value of the instrumentName property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getInstrumentName() {
        return instrumentName;
    }

    /**
     * Sets the value of the instrumentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setInstrumentName(java.lang.String value) {
        this.instrumentName = value;
    }

    /**
     * Gets the value of the instrumentAbbreviation property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getInstrumentAbbreviation() {
        return instrumentAbbreviation;
    }

    /**
     * Sets the value of the instrumentAbbreviation property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setInstrumentAbbreviation(java.lang.String value) {
        this.instrumentAbbreviation = value;
    }

    /**
     * Gets the value of the instrumentSound property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getInstrumentSound() {
        return instrumentSound;
    }

    /**
     * Sets the value of the instrumentSound property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setInstrumentSound(java.lang.String value) {
        this.instrumentSound = value;
    }

    /**
     * Gets the value of the solo property.
     * 
     * @return
     *     possible object is
     *     {@link Solo }
     *     
     */
    public Solo getSolo() {
        return solo;
    }

    /**
     * Sets the value of the solo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Solo }
     *     
     */
    public void setSolo(Solo value) {
        this.solo = value;
    }

    /**
     * Gets the value of the ensemble property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getEnsemble() {
        return ensemble;
    }

    /**
     * Sets the value of the ensemble property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setEnsemble(java.lang.String value) {
        this.ensemble = value;
    }

    /**
     * Gets the value of the virtualInstrument property.
     * 
     * @return
     *     possible object is
     *     {@link VirtualInstrument }
     *     
     */
    public VirtualInstrument getVirtualInstrument() {
        return virtualInstrument;
    }

    /**
     * Sets the value of the virtualInstrument property.
     * 
     * @param value
     *     allowed object is
     *     {@link VirtualInstrument }
     *     
     */
    public void setVirtualInstrument(VirtualInstrument value) {
        this.virtualInstrument = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setId(java.lang.String value) {
        this.id = value;
    }

}
