//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.02 at 04:43:05 PM EST 
//


package MusicXMLClasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}left-divider"/&gt;
 *         &lt;element ref="{}right-divider"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "leftDivider",
    "rightDivider"
})
@XmlRootElement(name = "system-dividers")
public class SystemDividers {

    @XmlElement(name = "left-divider", required = true)
    protected LeftDivider leftDivider;
    @XmlElement(name = "right-divider", required = true)
    protected RightDivider rightDivider;

    /**
     * Gets the value of the leftDivider property.
     * 
     * @return
     *     possible object is
     *     {@link LeftDivider }
     *     
     */
    public LeftDivider getLeftDivider() {
        return leftDivider;
    }

    /**
     * Sets the value of the leftDivider property.
     * 
     * @param value
     *     allowed object is
     *     {@link LeftDivider }
     *     
     */
    public void setLeftDivider(LeftDivider value) {
        this.leftDivider = value;
    }

    /**
     * Gets the value of the rightDivider property.
     * 
     * @return
     *     possible object is
     *     {@link RightDivider }
     *     
     */
    public RightDivider getRightDivider() {
        return rightDivider;
    }

    /**
     * Sets the value of the rightDivider property.
     * 
     * @param value
     *     allowed object is
     *     {@link RightDivider }
     *     
     */
    public void setRightDivider(RightDivider value) {
        this.rightDivider = value;
    }

}
